import coreWebVitals from 'eslint-config-next/core-web-vitals'
import typescript from 'eslint-config-next/typescript'

/** Flat config (ESLint 10) using the configs shipped by Next.js 16. */
const config = [
  ...coreWebVitals,
  ...typescript,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    },
  },
  {
    // The seed script is a CLI tool: printing progress is its purpose.
    files: ['src/scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // Generated by Payload — not hand-maintained.
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
      'src/migrations/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },
]

export default config
