/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'expertise-areas': ExpertiseArea;
    experiences: Experience;
    insights: Insight;
    categories: Category;
    books: Book;
    businesses: Business;
    engagements: Engagement;
    credentials: Credential;
    'legal-pages': LegalPage;
    media: Media;
    documents: Document;
    'contact-submissions': ContactSubmission;
    subscribers: Subscriber;
    orders: Order;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'expertise-areas': ExpertiseAreasSelect<false> | ExpertiseAreasSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    engagements: EngagementsSelect<false> | EngagementsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'de') | ('en' | 'fr' | 'de')[];
  globals: {
    'site-settings': SiteSetting;
    appearance: Appearance;
    'shop-settings': ShopSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    appearance: AppearanceSelect<false> | AppearanceSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: 'en' | 'fr' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The areas of intervention listed on /expertise and on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertise-areas".
 */
export interface ExpertiseArea {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * One or two sentences, shown on cards.
   */
  summary: string;
  /**
   * Line icon used on the expertise cards.
   */
  icon?: ('chart' | 'magnifier' | 'growth' | 'plan' | 'spark' | 'coins' | 'building' | 'people') | null;
  featuredOnHome?: boolean | null;
  /**
   * Ascending display order.
   */
  order?: number | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  /**
   * Introduction shown at the top of the dedicated page.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenges?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  audiences?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photographs and illustrations. Every image needs an alternative text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows, for screen readers and search engines. Type "-" only for a purely decorative image.
   */
  alt: string;
  /**
   * Photographer or source, when required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    book?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Assignments and projects. Results must only be filled in once they have been verified.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  type: 'assignment' | 'project';
  /**
   * Organisation name. Third-party logos are never displayed.
   */
  organisation: string;
  role: string;
  /**
   * Used by the sector filter, e.g. "Public finance".
   */
  sector?: string | null;
  region: 'europe' | 'africa' | 'international';
  /**
   * Pick the country: it appears on the experience map and its name is shown automatically in each language.
   */
  countries?:
    | {
        code?:
          | (
              | 'AD'
              | 'AE'
              | 'AF'
              | 'AG'
              | 'AI'
              | 'AL'
              | 'AM'
              | 'AO'
              | 'AR'
              | 'AT'
              | 'AU'
              | 'AW'
              | 'AZ'
              | 'BA'
              | 'BB'
              | 'BD'
              | 'BE'
              | 'BF'
              | 'BG'
              | 'BH'
              | 'BI'
              | 'BJ'
              | 'BN'
              | 'BO'
              | 'BR'
              | 'BS'
              | 'BT'
              | 'BW'
              | 'BY'
              | 'BZ'
              | 'CA'
              | 'CD'
              | 'CF'
              | 'CG'
              | 'CH'
              | 'CI'
              | 'CL'
              | 'CM'
              | 'CN'
              | 'CO'
              | 'CR'
              | 'CU'
              | 'CV'
              | 'CY'
              | 'CZ'
              | 'DE'
              | 'DJ'
              | 'DK'
              | 'DM'
              | 'DO'
              | 'DZ'
              | 'EC'
              | 'EE'
              | 'EG'
              | 'ER'
              | 'ES'
              | 'ET'
              | 'FI'
              | 'FJ'
              | 'FR'
              | 'GA'
              | 'GB'
              | 'GD'
              | 'GE'
              | 'GH'
              | 'GM'
              | 'GN'
              | 'GQ'
              | 'GR'
              | 'GT'
              | 'GW'
              | 'GY'
              | 'HN'
              | 'HR'
              | 'HT'
              | 'HU'
              | 'ID'
              | 'IE'
              | 'IL'
              | 'IN'
              | 'IQ'
              | 'IR'
              | 'IS'
              | 'IT'
              | 'JM'
              | 'JO'
              | 'JP'
              | 'KE'
              | 'KG'
              | 'KH'
              | 'KM'
              | 'KN'
              | 'KP'
              | 'KR'
              | 'KW'
              | 'KZ'
              | 'LA'
              | 'LB'
              | 'LC'
              | 'LI'
              | 'LK'
              | 'LR'
              | 'LS'
              | 'LT'
              | 'LU'
              | 'LV'
              | 'LY'
              | 'MA'
              | 'MC'
              | 'MD'
              | 'ME'
              | 'MG'
              | 'MH'
              | 'MK'
              | 'ML'
              | 'MM'
              | 'MN'
              | 'MR'
              | 'MT'
              | 'MU'
              | 'MV'
              | 'MW'
              | 'MX'
              | 'MY'
              | 'MZ'
              | 'NA'
              | 'NE'
              | 'NG'
              | 'NI'
              | 'NL'
              | 'NO'
              | 'NP'
              | 'NZ'
              | 'OM'
              | 'PA'
              | 'PE'
              | 'PG'
              | 'PH'
              | 'PK'
              | 'PL'
              | 'PT'
              | 'PY'
              | 'QA'
              | 'RO'
              | 'RS'
              | 'RU'
              | 'RW'
              | 'SA'
              | 'SB'
              | 'SC'
              | 'SD'
              | 'SE'
              | 'SG'
              | 'SI'
              | 'SK'
              | 'SL'
              | 'SM'
              | 'SN'
              | 'SO'
              | 'SR'
              | 'SS'
              | 'ST'
              | 'SV'
              | 'SY'
              | 'SZ'
              | 'TD'
              | 'TG'
              | 'TH'
              | 'TJ'
              | 'TL'
              | 'TM'
              | 'TN'
              | 'TR'
              | 'TT'
              | 'TW'
              | 'TZ'
              | 'UA'
              | 'UG'
              | 'US'
              | 'UY'
              | 'UZ'
              | 'VA'
              | 'VC'
              | 'VE'
              | 'VN'
              | 'VU'
              | 'WS'
              | 'YE'
              | 'ZA'
              | 'ZM'
              | 'ZW'
            )
          | null;
        /**
         * Leave empty for the official name. Fill in for a region or a city.
         */
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  startDate: string;
  /**
   * Leave empty for an ongoing assignment.
   */
  endDate?: string | null;
  /**
   * Shown on the cards and in the list.
   */
  summary: string;
  featured?: boolean | null;
  /**
   * Ascending display order.
   */
  order?: number | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  context?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Results are only displayed on the website when this box is checked. Never publish unverified figures.
   */
  resultsValidated?: boolean | null;
  results?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  expertiseAreas?: (number | ExpertiseArea)[] | null;
  relatedInsights?: (number | Insight)[] | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Editorial hub. Save as draft, preview, then publish or schedule.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Teaser used in listings and social cards.
   */
  excerpt: string;
  /**
   * Landscape, at least 1600×900 px.
   */
  coverImage?: (number | null) | Media;
  category: number | Category;
  author?: string | null;
  /**
   * A future date schedules the publication when the entry is published.
   */
  publishedAt?: string | null;
  /**
   * Highlight at the top of RK Insights.
   */
  featured?: boolean | null;
  /**
   * Computed on save (minutes).
   */
  readingTime?: number | null;
  /**
   * On publication (or at the scheduled date) the article is sent once to confirmed subscribers, in their language.
   */
  sendNewsletter?: boolean | null;
  newsletterSentAt?: string | null;
  newsletterRecipients?: number | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedExpertise?: (number | ExpertiseArea)[] | null;
  relatedInsights?: (number | Insight)[] | null;
  relatedBooks?: (number | Book)[] | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  subtitle?: string | null;
  author: string;
  /**
   * Portrait format.
   */
  cover?: (number | null) | Media;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  audience?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Language(s) the book is published in.
   */
  bookLanguage?: ('en' | 'fr' | 'de')[] | null;
  format?: ('paperback' | 'hardcover' | 'ebook' | 'audiobook')[] | null;
  /**
   * ISBN-13 when available.
   */
  isbn?: string | null;
  /**
   * Publishing house or "Self-published".
   */
  publisher?: string | null;
  publicationDate?: string | null;
  pages?: number | null;
  /**
   * Leave empty when the price is set by the retailer.
   */
  price?: number | null;
  currency?: ('EUR' | 'USD' | 'XAF') | null;
  availability: 'available' | 'preorder' | 'comingSoon' | 'outOfStock';
  /**
   * Empty = not tracked. Decreases with each paid order; at 0 the book becomes "Out of stock".
   */
  stock?: number | null;
  /**
   * External = link to a retailer. Direct = cart and payment on this website (Stripe / PayPal) once the shop is opened in Shop → Settings and the payment keys are configured; until then the site announces direct sales as "coming soon".
   */
  saleType: 'external' | 'direct' | 'none';
  purchaseLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional.
   */
  previewPdf?: (number | null) | Document;
  relatedBooks?: (number | Book)[] | null;
  featured?: boolean | null;
  /**
   * Ascending display order.
   */
  order?: number | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Label shown on the download button.
   */
  title: string;
  kind: 'expert-profile' | 'cv' | 'book-extract' | 'other';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * RK Business Consulting, RK IMMO-FINANZ, Kenmogne Strategic Publishing, KAILI Institut, KAILI Event. Uncheck "Active" to hide a venture temporarily.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  tagline?: string | null;
  description: string;
  valueProposition?: string | null;
  /**
   * e.g. Advisory, Real estate financing.
   */
  field?: string | null;
  audience?: string | null;
  /**
   * Full URL, or leave empty.
   */
  website?: string | null;
  contactEmail?: string | null;
  logo?: (number | null) | Media;
  /**
   * Uncheck to hide from the public site.
   */
  active?: boolean | null;
  /**
   * Ascending display order.
   */
  order?: number | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Talks, workshops, panels, interviews, podcasts, videos and press articles. Public page: Speaking & Media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements".
 */
export interface Engagement {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  type: 'conference' | 'workshop' | 'panel' | 'interview' | 'podcast' | 'video' | 'press';
  /**
   * A future date lists the engagement under "Upcoming".
   */
  date: string;
  endDate?: string | null;
  summary: string;
  eventName?: string | null;
  organiser?: string | null;
  /**
   * Leave empty for an online engagement.
   */
  city?: string | null;
  country?:
    | (
        | 'AD'
        | 'AE'
        | 'AF'
        | 'AG'
        | 'AI'
        | 'AL'
        | 'AM'
        | 'AO'
        | 'AR'
        | 'AT'
        | 'AU'
        | 'AW'
        | 'AZ'
        | 'BA'
        | 'BB'
        | 'BD'
        | 'BE'
        | 'BF'
        | 'BG'
        | 'BH'
        | 'BI'
        | 'BJ'
        | 'BN'
        | 'BO'
        | 'BR'
        | 'BS'
        | 'BT'
        | 'BW'
        | 'BY'
        | 'BZ'
        | 'CA'
        | 'CD'
        | 'CF'
        | 'CG'
        | 'CH'
        | 'CI'
        | 'CL'
        | 'CM'
        | 'CN'
        | 'CO'
        | 'CR'
        | 'CU'
        | 'CV'
        | 'CY'
        | 'CZ'
        | 'DE'
        | 'DJ'
        | 'DK'
        | 'DM'
        | 'DO'
        | 'DZ'
        | 'EC'
        | 'EE'
        | 'EG'
        | 'ER'
        | 'ES'
        | 'ET'
        | 'FI'
        | 'FJ'
        | 'FR'
        | 'GA'
        | 'GB'
        | 'GD'
        | 'GE'
        | 'GH'
        | 'GM'
        | 'GN'
        | 'GQ'
        | 'GR'
        | 'GT'
        | 'GW'
        | 'GY'
        | 'HN'
        | 'HR'
        | 'HT'
        | 'HU'
        | 'ID'
        | 'IE'
        | 'IL'
        | 'IN'
        | 'IQ'
        | 'IR'
        | 'IS'
        | 'IT'
        | 'JM'
        | 'JO'
        | 'JP'
        | 'KE'
        | 'KG'
        | 'KH'
        | 'KM'
        | 'KN'
        | 'KP'
        | 'KR'
        | 'KW'
        | 'KZ'
        | 'LA'
        | 'LB'
        | 'LC'
        | 'LI'
        | 'LK'
        | 'LR'
        | 'LS'
        | 'LT'
        | 'LU'
        | 'LV'
        | 'LY'
        | 'MA'
        | 'MC'
        | 'MD'
        | 'ME'
        | 'MG'
        | 'MH'
        | 'MK'
        | 'ML'
        | 'MM'
        | 'MN'
        | 'MR'
        | 'MT'
        | 'MU'
        | 'MV'
        | 'MW'
        | 'MX'
        | 'MY'
        | 'MZ'
        | 'NA'
        | 'NE'
        | 'NG'
        | 'NI'
        | 'NL'
        | 'NO'
        | 'NP'
        | 'NZ'
        | 'OM'
        | 'PA'
        | 'PE'
        | 'PG'
        | 'PH'
        | 'PK'
        | 'PL'
        | 'PT'
        | 'PY'
        | 'QA'
        | 'RO'
        | 'RS'
        | 'RU'
        | 'RW'
        | 'SA'
        | 'SB'
        | 'SC'
        | 'SD'
        | 'SE'
        | 'SG'
        | 'SI'
        | 'SK'
        | 'SL'
        | 'SM'
        | 'SN'
        | 'SO'
        | 'SR'
        | 'SS'
        | 'ST'
        | 'SV'
        | 'SY'
        | 'SZ'
        | 'TD'
        | 'TG'
        | 'TH'
        | 'TJ'
        | 'TL'
        | 'TM'
        | 'TN'
        | 'TR'
        | 'TT'
        | 'TW'
        | 'TZ'
        | 'UA'
        | 'UG'
        | 'US'
        | 'UY'
        | 'UZ'
        | 'VA'
        | 'VC'
        | 'VE'
        | 'VN'
        | 'VU'
        | 'WS'
        | 'YE'
        | 'ZA'
        | 'ZM'
        | 'ZW'
      )
    | null;
  languages?: ('fr' | 'en' | 'de')[] | null;
  /**
   * Real photo of the engagement or event visual (landscape). Also used as the preview before the video plays.
   */
  cover?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Video link. It loads only when the visitor clicks, in no-cookie mode.
   */
  videoUrl?: string | null;
  /**
   * Podcast, article, event page…
   */
  externalUrl?: string | null;
  externalLabel?: string | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Diplomas and certifications. Only add entries that can be evidenced — never approximate a title.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  title: string;
  institution: string;
  kind: 'education' | 'credential';
  /**
   * e.g. "2018 – 2020".
   */
  year?: string | null;
  location?: string | null;
  description?: string | null;
  /**
   * Ascending display order.
   */
  order?: number | null;
  /**
   * Checked for the starter content delivered with the website. Uncheck once the entry contains validated information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Structural drafts. The final wording must be validated by the owner and, where required, by a legal professional.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  /**
   * URL segment. Leave empty to generate it from the title.
   */
  slug: string;
  type: 'imprint' | 'privacy' | 'cookies' | 'terms' | 'returns';
  /**
   * While checked, a visible notice tells visitors the text is a draft and the page stays out of search engines.
   */
  needsLegalReview?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  lastUpdated?: string | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Requests received through the "Work With Me" form. Data protection: a request left unchanged for 24 months (configurable) is deleted automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  organisation?: string | null;
  email: string;
  country: string;
  requestType:
    | 'consulting'
    | 'dueDiligence'
    | 'advisory'
    | 'projectManagement'
    | 'smeProgramme'
    | 'training'
    | 'speaking'
    | 'partnership'
    | 'other';
  subject: string;
  message: string;
  /**
   * Language the visitor used.
   */
  locale?: string | null;
  status?: ('new' | 'inProgress' | 'answered' | 'archived') | null;
  /**
   * Whether the notification e-mail could actually be sent.
   */
  emailDelivered?: boolean | null;
  /**
   * Timestamp of the privacy consent.
   */
  consentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * RK Insights newsletter sign-ups, confirmed by e-mail (double opt-in). Only "Confirmed" subscribers receive articles. Unconfirmed sign-ups are deleted after 7 days, unsubscribed addresses after 30 days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  locale: 'fr' | 'de' | 'en';
  /**
   * Set to "Unsubscribed" to remove an address on request.
   */
  status: 'pending' | 'confirmed' | 'unsubscribed';
  consentAt?: string | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Direct sale orders. "Paid" = payment confirmed by Stripe or PayPal: ship the book, then set the status to "Shipped" (the buyer gets an e-mail, with the tracking link if filled in). Refunds are made in Stripe or PayPal, then set "Refunded".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  status: 'pending' | 'paid' | 'shipped' | 'cancelled' | 'refunded';
  /**
   * Optional carrier https:// link, to fill in before setting "Shipped".
   */
  trackingUrl?: string | null;
  provider?: ('stripe' | 'paypal') | null;
  providerRef?: string | null;
  locale?: string | null;
  customerName?: string | null;
  customerEmail?: string | null;
  shipping?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    postalCode?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
  };
  items?:
    | {
        book?: (number | null) | Book;
        title: string;
        quantity: number;
        unitPrice: number;
        lineTotal: number;
        id?: string | null;
      }[]
    | null;
  total: number;
  vatRate?: number | null;
  vatAmount?: number | null;
  currency?: string | null;
  paidAt?: string | null;
  shippedAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Only an administrator can change a role.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'expertise-areas';
        value: number | ExpertiseArea;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'engagements';
        value: number | Engagement;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertise-areas_select".
 */
export interface ExpertiseAreasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  featuredOnHome?: T;
  order?: T;
  isPlaceholder?: T;
  intro?: T;
  challenges?:
    | T
    | {
        item?: T;
        id?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  audiences?:
    | T
    | {
        item?: T;
        id?: T;
      };
  approach?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  organisation?: T;
  role?: T;
  sector?: T;
  region?: T;
  countries?:
    | T
    | {
        code?: T;
        name?: T;
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  summary?: T;
  featured?: T;
  order?: T;
  isPlaceholder?: T;
  context?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  resultsValidated?: T;
  results?:
    | T
    | {
        item?: T;
        id?: T;
      };
  expertiseAreas?: T;
  relatedInsights?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  featured?: T;
  readingTime?: T;
  sendNewsletter?: T;
  newsletterSentAt?: T;
  newsletterRecipients?: T;
  isPlaceholder?: T;
  content?: T;
  relatedExpertise?: T;
  relatedInsights?: T;
  relatedBooks?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  author?: T;
  cover?: T;
  summary?: T;
  description?: T;
  audience?:
    | T
    | {
        item?: T;
        id?: T;
      };
  bookLanguage?: T;
  format?: T;
  isbn?: T;
  publisher?: T;
  publicationDate?: T;
  pages?: T;
  price?: T;
  currency?: T;
  availability?: T;
  stock?: T;
  saleType?: T;
  purchaseLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  previewPdf?: T;
  relatedBooks?: T;
  featured?: T;
  order?: T;
  isPlaceholder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  valueProposition?: T;
  field?: T;
  audience?: T;
  website?: T;
  contactEmail?: T;
  logo?: T;
  active?: T;
  order?: T;
  isPlaceholder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements_select".
 */
export interface EngagementsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  date?: T;
  endDate?: T;
  summary?: T;
  eventName?: T;
  organiser?: T;
  city?: T;
  country?: T;
  languages?: T;
  cover?: T;
  featured?: T;
  isPlaceholder?: T;
  description?: T;
  videoUrl?: T;
  externalUrl?: T;
  externalLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  title?: T;
  institution?: T;
  kind?: T;
  year?: T;
  location?: T;
  description?: T;
  order?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  needsLegalReview?: T;
  content?: T;
  lastUpdated?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        book?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  organisation?: T;
  email?: T;
  country?: T;
  requestType?: T;
  subject?: T;
  message?: T;
  locale?: T;
  status?: T;
  emailDelivered?: T;
  consentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  status?: T;
  consentAt?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  trackingUrl?: T;
  provider?: T;
  providerRef?: T;
  locale?: T;
  customerName?: T;
  customerEmail?: T;
  shipping?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        postalCode?: T;
        city?: T;
        state?: T;
        country?: T;
      };
  items?:
    | T
    | {
        book?: T;
        title?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  total?: T;
  vatRate?: T;
  vatAmount?: T;
  currency?: T;
  paidAt?: T;
  shippedAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, contact details, social profiles and default SEO metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  /**
   * Positioning shown under the name.
   */
  headline: string;
  /**
   * Kept in English in every language.
   */
  signature: string;
  logo?: (number | null) | Media;
  /**
   * PDF offered by the "Download Expert Profile" buttons. While empty, the buttons explain that the document is not published yet.
   */
  expertProfile?: (number | null) | Document;
  /**
   * Optional.
   */
  cvDocument?: (number | null) | Document;
  /**
   * Notice shown at the very bottom of every page ("© by [name]. All rights reserved."). Empty: "© year Romial Kenmogne" instead.
   */
  creditName?: string | null;
  /**
   * Optional full URL: turns the credit into a link.
   */
  creditUrl?: string | null;
  /**
   * Published professional e-mail. Leave empty until confirmed.
   */
  email?: string | null;
  phone?: string | null;
  /**
   * Shown in the footer.
   */
  address?: string | null;
  /**
   * Where contact requests are delivered. Falls back to the EMAIL_TO environment variable.
   */
  notificationEmail?: string | null;
  /**
   * e.g. "French, English, German".
   */
  spokenLanguages?: string | null;
  /**
   * Booking page of an external tool (Cal.com, Calendly…), full https:// address. A "Book a call" button then appears on the Contact and About pages; the tool opens in a new tab and nothing is loaded before the click. Empty: no button.
   */
  bookingUrl?: string | null;
  /**
   * e.g. "Book 30 minutes". Empty: "Book a call".
   */
  bookingLabel?: string | null;
  social?:
    | {
        platform: 'linkedin' | 'x' | 'facebook' | 'youtube' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used as a title suffix on inner pages.
   */
  defaultSeoTitle?: string | null;
  defaultSeoDescription?: string | null;
  /**
   * 1200×630 pixels.
   */
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Colours, heading font and home-page background of the public site. Text always stays readable: its colours are adjusted automatically (WCAG AA). Changes show on the site within seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance".
 */
export interface Appearance {
  id: number;
  /**
   * Choose "Custom" to set your own colours. An empty colour falls back to the Signature palette.
   */
  palette: 'signature' | 'ivory' | 'anthracite' | 'petrol' | 'forest' | 'burgundy' | 'custom';
  light?: {
    /**
     * Headings, text, buttons and dark bands (footer).
     */
    primary?: string | null;
    /**
     * Rules, links and gold buttons.
     */
    accent?: string | null;
    /**
     * Subtitles and supporting text.
     */
    textSecondary?: string | null;
    background?: string | null;
    backgroundSubtle?: string | null;
  };
  dark?: {
    background?: string | null;
    backgroundSubtle?: string | null;
    accent?: string | null;
  };
  /**
   * Body text stays in Inter for comfortable reading.
   */
  headingFont: 'source-serif' | 'playfair' | 'inter';
  hero: {
    style: 'halo' | 'plain' | 'image';
    /**
     * Decorative photo (office, city, texture…), ideally 2400 px wide. It is veiled with the background colour so the text stays readable. Do not use generated portraits.
     */
    image?: (number | null) | Media;
    intensity?: ('subtle' | 'visible') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Direct book sales. Payments go through Stripe (card, Apple Pay, Google Pay…) and PayPal; their keys are configured on the server. While they are missing the site shows no payment, even if the shop is enabled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  /**
   * Shows "Add to cart" on books set to "Direct sale" (EUR price, available or pre-order). Tick only once the terms of sale and the returns policy are validated.
   */
  enabled?: boolean | null;
  /**
   * To be confirmed by the accountant. 0 = no VAT shown (e.g. small business scheme); 7 = German reduced rate for books. Book prices are always gross prices.
   */
  vatRate?: number | null;
  /**
   * Address receiving each new paid order. Falls back to EMAIL_TO.
   */
  notificationEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, value proposition and closing call to action.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Small line above the name, e.g. the geographic scope.
   */
  heroEyebrow?: string | null;
  /**
   * One clear sentence: what you do and for whom.
   */
  heroValueProposition?: string | null;
  /**
   * Professional photograph. While empty, an elegant placeholder is displayed — no invented portrait is ever generated.
   */
  heroPortrait?: (number | null) | Media;
  /**
   * Short factual markers (e.g. "Languages — FR / EN / DE"). Never invent figures.
   */
  heroKeyPoints?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  expertiseIntro?: string | null;
  experienceIntro?: string | null;
  ecosystemIntro?: string | null;
  finalCtaTitle?: string | null;
  finalCtaBody?: string | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Executive biography, career path, vision, languages and regions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  lead?: string | null;
  portrait?: (number | null) | Media;
  biography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  career?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  vision?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language: string;
        /**
         * e.g. "Native", "Professional".
         */
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  regions?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional overrides. When empty, the title and summary of the entry are used.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 120–160 characters.
     */
    description?: string | null;
    /**
     * Social sharing image (1200×630). Falls back to the site default.
     */
    image?: (number | null) | Media;
    /**
     * Exclude this entry from search engines and from the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  headline?: T;
  signature?: T;
  logo?: T;
  expertProfile?: T;
  cvDocument?: T;
  creditName?: T;
  creditUrl?: T;
  email?: T;
  phone?: T;
  address?: T;
  notificationEmail?: T;
  spokenLanguages?: T;
  bookingUrl?: T;
  bookingLabel?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance_select".
 */
export interface AppearanceSelect<T extends boolean = true> {
  palette?: T;
  light?:
    | T
    | {
        primary?: T;
        accent?: T;
        textSecondary?: T;
        background?: T;
        backgroundSubtle?: T;
      };
  dark?:
    | T
    | {
        background?: T;
        backgroundSubtle?: T;
        accent?: T;
      };
  headingFont?: T;
  hero?:
    | T
    | {
        style?: T;
        image?: T;
        intensity?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  enabled?: T;
  vatRate?: T;
  notificationEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroValueProposition?: T;
  heroPortrait?: T;
  heroKeyPoints?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  expertiseIntro?: T;
  experienceIntro?: T;
  ecosystemIntro?: T;
  finalCtaTitle?: T;
  finalCtaBody?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  lead?: T;
  portrait?: T;
  biography?: T;
  career?: T;
  vision?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  regions?:
    | T
    | {
        name?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'insights';
          value: number | Insight;
        } | null)
      | ({
          relationTo: 'engagements';
          value: number | Engagement;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}